# Generated by Django 4.2.1 on 2024-01-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testdb", "0002_banks"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="road_defect_images/"
            ),
        ),
    ]
