# Generated by Django 4.2.1 on 2024-01-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testdb", "0004_employee_image_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.CharField(max_length=20)),
                ("etype", models.CharField(max_length=255)),
                ("edescription", models.TextField()),
                ("lat", models.DecimalField(decimal_places=10, max_digits=19)),
                ("lng", models.DecimalField(decimal_places=10, max_digits=19)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="road_defect_images/"
                    ),
                ),
                (
                    "image_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "road_data",
            },
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Banks",
        ),
    ]
