# Generated by Django 4.2.1 on 2024-02-04 01:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("testdb", "0006_remove_roaddata_eid_roaddata_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Road",
            fields=[
                ("road_id", models.AutoField(primary_key=True, serialize=False)),
                ("road_name", models.CharField(max_length=255)),
                ("road_type", models.CharField(max_length=50)),
                ("start_measure", models.FloatField()),
                ("end_measure", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("user_role", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Sign",
            fields=[
                ("sign_id", models.AutoField(primary_key=True, serialize=False)),
                ("sign_type", models.CharField(max_length=50)),
                ("installation_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testdb.road"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("update_date", models.DateTimeField()),
                ("graph_changes", models.JSONField()),
                ("attribute_changes", models.JSONField()),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testdb.road"
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testdb.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                ("query_id", models.AutoField(primary_key=True, serialize=False)),
                ("query_date", models.DateTimeField()),
                ("query_type", models.CharField(max_length=50)),
                ("query_details", models.JSONField()),
                ("results", models.JSONField()),
                (
                    "road_defect_type",
                    models.CharField(
                        choices=[
                            ("Pothole", "Pothole"),
                            ("Crack", "Crack"),
                            ("Sinkhole", "Sinkhole"),
                            ("Surface Erosion", "Surface Erosion"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testdb.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                ("inspection_id", models.AutoField(primary_key=True, serialize=False)),
                ("inspection_date", models.DateField()),
                ("surface_malformations", models.JSONField()),
                ("sign_damages", models.JSONField()),
                ("safety_device_damages", models.JSONField()),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testdb.user"
                    ),
                ),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testdb.road"
                    ),
                ),
            ],
        ),
    ]
