# Generated by Django 4.2.1 on 2024-01-29 23:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testdb", "0007_roaddatafinals_delete_roaddata"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RoadDataFinals",
            new_name="RoadData",
        ),
        migrations.AlterModelTable(
            name="roaddata",
            table="road_data",
        ),
    ]
