# Generated by Django 5.0.1 on 2024-02-04 16:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testdb", "0007_road_user_sign_roadhistory_query_inspection"),
    ]

    operations = [
        migrations.AddField(
            model_name="roaddata",
            name="geometry",
            field=django.contrib.gis.db.models.fields.LineStringField(
                default="SRID=4326;LINESTRING(0 0, 1 1)", srid=4326
            ),
        ),
    ]
