# Generated by Django 4.2.1 on 2024-01-29 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testdb", "0008_rename_roaddatafinals_roaddata_alter_roaddata_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadDataFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etype", models.CharField(max_length=255)),
                ("edescription", models.TextField()),
                ("lat", models.DecimalField(decimal_places=10, max_digits=19)),
                ("lng", models.DecimalField(decimal_places=10, max_digits=19)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="road_defect_images/"
                    ),
                ),
                (
                    "image_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "road_data_final",
            },
        ),
    ]
