# Generated by Django 4.2.1 on 2024-01-29 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testdb", "0009_roaddatafinal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoadDataFinal",
        ),
    ]
